### ISSUE TITLE
Plugin not showing buttons

### ISSUE THREAD

**Issue by mayolag** [pkp/addThis#13]
I already installed and configured the plugin, but nothing shows anywhere. Help please. This is my page: http://revistarelap.org.

**Comment by asmecher** [comment]
@mayolag, how did you install the plugin? What version of OJS are you using?

**Comment by mayolag** [comment]
I installed it via ftp (downloaded at GitHub, unzipped and uploaded to
plugins/generic/addThis), I'm using OJS 3.1.1.4.

**Comment by asmecher** [comment]
@mayolag, installing the plugin that way won't register it properly. I'd recommend installing it via the plugin gallery inside OJS.

**Comment by mayolag** [comment]
I can’t install any plugin that way because the ojs has some kind of bug, I
tried to reinstall it and didn’t work, so I opted to install plugins via
ftp. I didn’t know some would not work that way. I need to have the share
buttons. What can I do then?

**Comment by asmecher** [comment]
Can you describe the problem you have with the plugin gallery?

**Comment by mayolag** [comment]
After clicking on install and then on the "ok" button within the pop-up
window, nothing happens.

**Comment by asmecher** [comment]
I suspect you'll find something in your PHP error log. I'd suggest checking in the support forum (https://forum.pkp.sfu.ca) to see if that message is already discussed there, and if not, open a new thread there -- if it turns out to be a bug, we can create a new issue for it here.

**Comment by mayolag** [comment]
Hello. I managed to install it, however the buttons only show in mobile.

**Comment by asmecher** [comment]
@mayolag, have you posted in the support forum?
