### ISSUE TITLE
Addthis & Googlescholar plugin in OJS 

### ISSUE THREAD

**Issue by 03155765774** [pkp/addThis#22]
Hello ,
I have installed addthis and google scholar plugin in OJS 3.2.1, after the successfully installed plugins do not work, neither the addthis (button shows ) in article details nor the published article show in google scholar, please help

**Comment by asmecher** [comment]
@03155765774, could you post your question in our support forum (https://forum.pkp.sfu.ca)? That's the best place to get help. Include the method you used to install the plugin, and what version of each plugin you're using.
