### ISSUE TITLE
Username or E-mail Address 

### ISSUE THREAD

**Issue by ruienf** [pkp/addThis#23]
Hi!

Sorry to bother you with this...

I'm not getting the statistics feedback in the plugin configuration -> Statistics

That led me to a question: is the username field my e-mail ou the account name?

When I login to AddThis I use the e-mail, but the plugin asks me for the username...

Thank you!

Rui Pedro Silva

**Comment by asmecher** [comment]
@ruienf, could you post support questions on our support forum (https://forum.pkp.sfu.ca) rather than the github issue tracker? We use this for tracking bugs and ongoing development.
